name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      #   uses: actions/github-script@v3
      #   with:
      #       github-token: ${{ secrets.GITHUB_TOKEN }}
      #       script: |
      #           github.issues.createComment({
      #               issue_number: context.issue.number,
      #               owner: context.repo.owner,
      #               repo: context.repo.repo,
      #               body: 'Thanks for opening this issue! I will look into it.'
      #           })
